name: logK
channels:
- pyg
- pytorch
- dglteam/label/cu117
- nvidia
- conda-forge
- defaults
dependencies:
- ca-certificates=2023.5.7
- certifi=2023.5.7
- deepchem=2.7.1
- dgl=1.0.2.cu117
- dgllife=0.3.2
- ipykernel=6.22.0
- loguru=0.7.0
- mamba=1.4.2
- molvs=0.1.1
- openssl=3.1.1
- optuna=3.1.1
- pandas=2.0.1
- pyg=2.3.0
- pytorch=2.0.0
- pytorch-lightning=2.0.2
- torch-scatter=2.1.1
- torchaudio=2.0.0
- torchvision=0.15.0
- tqdm=4.65.0
- pip:
  - absl-py==1.4.0
  - aiohttp==3.8.4
  - aiosignal==1.3.1
  - altair==5.0.1
  - anyio==3.6.2
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - arrow==1.2.3
  - async-timeout==4.0.2
  - attrs==23.1.0
  - backoff==2.2.1
  - backports-zoneinfo==0.2.1
  - beautifulsoup4==4.12.2
  - bleach==6.0.0
  - blinker==1.6.2
  - cachedmethods==0.1.4
  - cachetools==5.3.0
  - cairocffi==1.5.1
  - cairosvg==2.7.0
  - cgrtools==4.0.41
  - chardet==3.0.4
  - cimtools==4.0.8
  - click==8.1.3
  - cohere==4.5.1
  - cssselect2==0.7.0
  - dataclasses-json==0.5.7
  - defusedxml==0.7.1
  - dig==0.1.10
  - docopt==0.6.2
  - exmol==3.0.2
  - fastjsonschema==2.16.3
  - fqdn==1.5.1
  - frozenlist==1.3.3
  - futures==3.0.5
  - gitdb==4.0.10
  - gitpython==3.1.31
  - google-auth==2.17.3
  - google-auth-oauthlib==1.0.0
  - grpcio==1.54.0
  - huggingface-hub==0.14.1
  - idna==2.8
  - ipympl==0.9.3
  - ipython==8.2.0
  - ipython-genutils==0.2.0
  - ipywidgets==8.0.6
  - isoduration==20.11.0
  - janus-ga==1.0.3
  - jsonschema==4.17.3
  - jupyter-events==0.6.3
  - jupyter-server==2.5.0
  - jupyter-server-terminals==0.4.4
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==3.0.7
  - langchain==0.0.171
  - llvmlite==0.40.0
  - lxml==4.9.2
  - markdown==3.4.3
  - markdown-it-py==2.2.0
  - marshmallow==3.19.0
  - marshmallow-enum==1.5.1
  - mdurl==0.1.2
  - mistune==2.0.5
  - multidict==6.0.4
  - mypy-extensions==1.0.0
  - nbclassic==1.0.0
  - nbclient==0.7.4
  - nbconvert==7.4.0
  - nbformat==5.8.0
  - notebook==6.5.4
  - notebook-shim==0.2.3
  - numba==0.57.0
  - numexpr==2.8.4
  - oauthlib==3.2.2
  - openai==0.27.6
  - openapi-schema-pydantic==1.2.4
  - pandocfilters==1.5.0
  - periodictable==1.6.1
  - pkgutil-resolve-name==1.3.10
  - prometheus-client==0.16.0
  - protobuf==3.20.3
  - pyarrow==12.0.0
  - pyasn1==0.5.0
  - pyasn1-modules==0.3.0
  - pydantic==1.10.7
  - pydeck==0.8.1b0
  - pyjnius==1.4.2
  - pympler==1.0.1
  - pyrsistent==0.19.3
  - pystow==0.5.0
  - python-json-logger==2.0.7
  - pytz-deprecation-shim==0.1.0.post0
  - ratelimit==2.2.1
  - rdkit==2023.3.1
  - requests==2.22.0
  - requests-oauthlib==1.3.1
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rich==13.4.1
  - rsa==4.9
  - scikit-learn==1.2.2
  - selfies==1.0.3
  - send2trash==1.8.2
  - skunk==1.2.0
  - slicer==0.0.7
  - smmap==5.0.0
  - sniffio==1.3.0
  - soupsieve==2.4.1
  - streamlit==1.23.1
  - streamlit-ketcher==0.0.1
  - synspace==0.3.0
  - tenacity==8.2.2
  - tensorboard==2.12.2
  - tensorboard-data-server==0.7.0
  - tensorboard-plugin-wit==1.8.1
  - tensorboardx==2.6
  - terminado==0.17.1
  - tinycss2==1.2.1
  - toml==0.10.2
  - typing-inspect==0.8.0
  - tzlocal==4.3
  - uri-template==1.2.0
  - urllib3==1.24.3
  - validators==0.20.0
  - watchdog==3.0.0
  - webcolors==1.13
  - webencodings==0.5.1
  - websocket-client==1.5.1
  - werkzeug==2.3.3
  - widget-periodictable==3.1.0
  - widgetsnbextension==4.0.7
  - yarl==1.9.2
