#!/bin/bash
metals=("Sc" "Y" "La" "Ce" "Pr" "Nd" "Pm" "Sm" "Eu" "Gd" "Tb" "Dy" "Ho" "Er" "Tm" "Yb" "Lu" "Ac" "Th" "Pa" "U" "Np" "Pu" "Am" "Cm" "Bk" "Cf")

check_metal() {
  metal=$1
  if [ -f outs/train_general_testonly_cond/${metal}.out ]; then
    echo "Output file for ${metal} already exists. Skipping."
    return 1
  fi

  if [ -f Output/WithCond/${metal}_*/metrics.json ]; then
    echo "Metrics file already exists for ${metal}. Skipping."
    return 1
  fi

  return 0
}
for metal in "${metals[@]}"; do
    while [ $(ps uaxw | grep "python train_general_testonly_cond.py" | grep -v grep | wc -l) -ge 2 ]; do
        sleep 1
    done
    if check_metal "${metal}"; then
      ( nohup python train_general_testonly_cond.py "${metal}" > outs/train_general_testonly_cond/${metal}.out & )
      echo "Started processing ${metal}"
      sleep 20
    fi
  done
