#!/bin/bash
metals=("Mg" "Al" "Ca" "Mn" "Fe" "Co" "Ni" "Cu" "Zn" "Y" "Ag" "Cd" "Hg" "Pb" "Bi" "La" "Ce" "Pr")

check_metal() {
  metal=$1
  if [ -f outs/train_general_testonly_${metal}.out ]; then
    echo "Output file for ${metal} already exists. Skipping."
    return 1
  fi

  if [ -f Output/NoFTransGeneralModel/${metal}_*/metrics.json ]; then
    echo "Metrics file already exists for ${metal}. Skipping."
    return 1
  fi

  return 0
}

for metal in "${metals[@]}"; do
  while [ $(ps uaxw | grep "python train_general_testonly.py" | grep -v grep | wc -l) -ge 3 ]; do
      sleep 1
  done
  if check_metal "${metal}"; then
    ( nohup python train_general_testonly.py "${metal}" > outs/train_general_testonly_${metal}.out & )
    echo "Started processing ${metal}"
    sleep 20
  fi
done
